#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# https://github.com/typicode/husky/issues/912#issuecomment-817522060
# sets the correct PATH before running hook for use nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm for general case
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm for brew case

npx commitlint --edit $1
