#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# https://typicode.github.io/husky/#/?id=command-not-found
# This loads nvm.sh and sets the correct PATH before running hook
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm for general case
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm for brew case

npx lint-staged
