name: Documentation Build

on:
  push:
    branches:
      - master
      - main

# allow actions to edit the project
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy project to machine
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6

      - name: Restore node_modules
        id: restore-node-modules
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: cache-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies
        if: steps.restore-node-modules.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Cache node_modules
        if: steps.restore-node-modules.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: node_modules
          key: ${{ steps.restore-node-modules.outputs.cache-primary-key }}

      - name: Build docs
        run: pnpm docs:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs-dist
          branch: gh-pages
          clean: true
          clean-exclude: CNAME
