name: Testing

on: push

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Copy project to machine
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node: 18

      - name: Restore node_modules
        id: restore-node-modules
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: cache-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        if: steps.restore-node-modules.outputs.cache-hit != 'true'
        run: yarn install

      - name: Cache node_modules
        if: steps.restore-node-modules.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: node_modules
          key: ${{ steps.restore-node-modules.outputs.cache-primary-key }}

      - name: Run lint
        run: yarn lint

      - name: Run testing with coverage
        run: yarn cov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
